version: "3.1"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: campdb-docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=campdemodb
    restart: unless-stopped
  # APP*****************************************
  campdemoapp:
    image: camp-demo:latest
    network_mode: bridge
    container_name: campdemo
    expose:
      - 8090
    ports:
      - 8090:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: