version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: campdb-docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=campdemodb
    restart: unless-stopped
  # APP*****************************************
  campdemoapp:
    image: camp-demo:latest
    expose:
      - 8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
  # NGINX
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - campdemoapp
    ports:
      - "8090:8090"
volumes:
  postgres-data: