# This workflow will build a Java project with Maven, upload artifact to github backup and push to docker repository
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: create directory
      run: mkdir staging && cp target/*.jar staging
    - name: package and upload
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jpcampos/bootprojects
        tag_with_ref: true
        tag_with_sha: true
    - name: Deploy to Docker swarm
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: root@66.42.67.233
        ssh_private_key: ${{ secrets.VULTR_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.VULTR_SSH_PUBLIC_KEY }}
        deployment_mode: docker-swarm
        copy_stack_file: true
        deploy_path: /opt/bin
        stack_file_name: docker-compose.yaml
        keep_files: 5
        args: up
